name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - published

env:
  docker_tag: kaiede/healthproxy:${{ github.event_name != 'release' && 'test' || 'latest' }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker - linux/${{ matrix.arch }}
    if: github.repository == 'Kaiede/healthproxy'
    strategy:
      matrix:
        arch: [amd64, arm64]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      if: matrix.arch != 'amd64'
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build ${{ matrix.arch }}
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./docker/Dockerfile
        platforms: linux/${{ matrix.arch }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.docker_tag }}-${{ matrix.arch }}
        build-args: |
          QEMU_CPU=max

  merge-tags:
    needs: ['build']
    runs-on: ubuntu-latest
    if: github.repository == 'Kaiede/healthproxy' && github.event_name != 'pull_request'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Merge Manifests
      if: github.event_name != 'pull_request'
      run: docker buildx imagetools create -t ${{ env.docker_tag }} ${{ env.docker_tag }}-amd64 ${{ env.docker_tag }}-arm64
